---

- name: Configure tzdata area in debconf
  sudo: yes
  debconf:
    name: 'tzdata'
    question: 'tzdata/Areas'
    vtype: 'select'
    value: '{{ ntp_timezone.split("/")[0] }}'
  register: ntp_debconf_set_area
  when: ntp_timezone is defined and ntp_timezone

- name: Configure tzdata zone in debconf
  sudo: yes
  debconf:
    name: 'tzdata'
    question: 'tzdata/Zones/{{ ntp_timezone.split("/")[0] }}'
    vtype: 'select'
    value: '{{ ntp_timezone.split("/")[1] }}'
  register: ntp_debconf_set_zone
  when: ntp_timezone is defined and ntp_timezone

  # tzdata ignores debconf answers when configured non-interactively
  # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=704089
- name: Configure timezone in /etc/timezone
  sudo: yes
  copy:
    content: '{{ ntp_timezone }}\n'
    dest: '/etc/timezone'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: ntp_etc_timezone
  when: ntp_timezone is defined and ntp_timezone

- name: Install required packages
  sudo: yes
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_items: [ 'tzdata' ]

- name: Reconfigure tzdata
  sudo: yes
  shell: dpkg-reconfigure --frontend noninteractive tzdata
  when: (ntp_timezone is defined and ntp_timezone) 
        # and
        #((ntp_debconf_set_area is defined and ntp_debconf_set_area.changed) or
        # (ntp_debconf_set_zone is defined and ntp_debconf_set_zone.changed) or
        # (ntp_etc_timezone is defined and ntp_etc_timezone.changed))

  # Install NTPd on all hosts except inside containers
- include: ntpd.yml
  sudo: yes
  when: (ntp_daemon == 'ntpd')
         # and (ansible_local|d() and
         #(ansible_local.root|d() and (ansible_local.root.flags | intersect(ntp_root_flags.cap_sys_time)) or
         #(ansible_local.cap12s|d() and (not ansible_local.cap12s.enabled | bool or
         #(ansible_local.cap12s.enabled | bool and 'cap_sys_time' in ansible_local.cap12s.list))))))

  # Install OpenNTPd on all hosts except inside containers
- include: openntpd.yml
  when: (ntp_daemon == 'openntpd')

