---

- name: Make sure that OpenNTPd is not installed
  apt:
    name: 'openntpd'
    state: 'absent'
    purge: True

- name: Install NTPd package
  apt:
    name: 'ntp'
    state: 'present'
    install_recommends: False

- name: Divert original /etc/ntp.conf
  command: dpkg-divert --quiet --local --divert /etc/ntp.conf.dpkg-divert
           --rename /etc/ntp.conf creates=/etc/ntp.conf.dpkg-divert

- name: Configure NTPd
  template:
    src: 'etc/ntpd/ntp.conf.j2'
    dest: '/etc/ntp.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart ntp' ]

